### ISSUE TITLE
[BUG] - array element with sequence, Blaupunkt Extreme

### ISSUE THREAD

**Issue by itslechef** [oven-lab/tuya_cloud_map_extractor#12]
Cannot add integration into home assistant due to unknown error.
During configuration of the integration in home assistant unknown error occurs with blaupunkt extreme

Log entry:
Logger: custom_components.tuya_cloud_map_extractor.config_flow
Source: custom_components/tuya_cloud_map_extractor/config_flow.py:58
Integration: Tuya Cloud Map Extractor (documentation, issues)
First occurred: 16:01:15 (5 occurrences)
Last logged: 16:02:28

setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (170, 216) + inhomogeneous part.
Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 58, in async_step_user
    info = await validate(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 95, in validate
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 93, in get_map
    return render_layout(header, map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 82, in render_layout
    array = to_array_custom0(pixellist, width, height)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 69, in to_array_custom0
    return np.array(pixels, dtype=np.uint8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (170, 216) + inhomogeneous part.

**Comment by oven-lab** [comment]
If you include the log entry starting with "Unsupported data type", I can take a look at it!

**Comment by itslechef** [comment]
[home-assistant_2023-12-17T15-23-52.278Z.log](https://github.com/oven-lab/tuya_cloud_map_extractor/files/13696678/home-assistant_2023-12-17T15-23-52.278Z.log)
Sadly this is all the logging im getting. Anything I can do to get you what you need?

**Comment by oven-lab** [comment]
That is quite weird, I will take a look at it. In the meantime, If you want, you could enable debug logging and send me the logs so i can look at it:

Enable debug logging:
![Enable debug](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/84805366/5b5ddab5-1d28-47e8-a71d-7bf10ab434ec)

Call service camera.turn_on
![camera tunr_on](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/84805366/64c87443-a68b-41a2-9642-79f53220f36a)

Disable debug logging:
![Disable debug](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/84805366/c42a6a11-c48f-47b8-801a-eb32c69d228d)

If the logs are not downloaded automatically, download the logs:
![Download logs](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/84805366/6dc0d987-2e88-427f-bacf-1e13d0c6d437)

And upload them here.

**Comment by itslechef** [comment]
![bluebot xtreme](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/95701619/a260beb8-38e0-48f7-84b2-1f16f1eecb75)
The problem arises before I can configure the integration at all, so I can't even turn on debug logging

**Comment by itslechef** [comment]
thanks for the quick replies. Redownloaded the integration in beta 7 and that seems to have fixed the issue!

**Comment by oven-lab** [comment]
Great!
