### ISSUE TITLE
[BUG] - Unknown Error, not able to install

### ISSUE THREAD

**Issue by BombeiJay** [oven-lab/tuya_cloud_map_extractor#13]
**Describe the bug**
Unkown error when adding to HA
All APIs are subscribed

**To Reproduce**
adding to HA with all fields filled with correct ids 

**Version:**
 - OS: Home Assistant OS via virtual machine
 - Version 2023.12.3

**Log entry**
AttributeError: 'TuyaVacuumEntity' object has no attribute 'async_start_pause'
2023-12-18 23:32:38.235 ERROR (MainThread) [custom_components.tuya_cloud_map_extractor.config_flow] list index out of range
Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 58, in async_step_user
    info = await validate(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 95, in validate
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 92, in get_map
    header, map = download_map(map_link)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 21, in download_map
    mapurl = url["result"][0]["map_url"]

**Comment by oven-lab** [comment]
Added more error logging in version v1.2.0 to help me diagnose the issue, if you want to try again.

**Comment by BombeiJay** [comment]
Heyy, first of all I would like to thank you for the integration, afterwards you will find the new logs.

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tuya_cloud_map_extractor.config_flow
Source: custom_components/tuya_cloud_map_extractor/config_flow.py:57
Integration: tuya_cloud_map_extractor (documentation, issues)
First occurred: 13:32:55 (1 occurrences)
Last logged: 13:32:55

list index out of range
Traceback (most recent call last):
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 57, in async_step_user
    headers, image = await validate(self.hass, user_input)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 214, in validate
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 131, in get_map
    raise e
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 127, in get_map
    map_link = link["result"][0]["map_url"]
               ~~~~~~~~~~~~~~^^^
IndexError: list index out of range



Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.main
Source: custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py:130
Integration: tuya_cloud_map_extractor (documentation, issues)
First occurred: 13:32:55 (1 occurrences)
Last logged: 13:32:55

Encountered an error, please include the following data in your github issue: b'eyJyZXN1bHQiOiBbXSwgInN1Y2Nlc3MiOiB0cnVlLCAidCI6IDE3MDMwNzU1NzUyMzksICJ0aWQiOiAiZTY1OTRlYWU5ZjMzMTFlZThhZTVlNjczMjAzZDAyMTEifQ=='

**Comment by oven-lab** [comment]
Well, you are very welcome. But you are probably about to get disapointed.

The error is at tuyas end. The links are:
`"result": []`

That is, there is no link. So it seems that either something is not set up correctly, or more likely, your vacuum doesn't upload it's map to tuya cloud. There should be some way to get it from the vacuum directly, which i will work on in the future, for an actual relatime map in homeassistant. But as for now, there is nothing i can do for you sadly. But i will make sure to send you a message when i get it working. But that is further in the future.

**Comment by BombeiJay** [comment]
Okay, but thanks anyway, I think I know what the problem is. I have the Philips Homerun 3000, Philips also has its own app for it (which is not supported in HA) but Philips uses Tuya to share the vacuum cleaner with Google etc., so I was able to add it to Smart Life and thus also in HA

**Comment by oven-lab** [comment]
It is possible that the files are still stored in the tuya cloud, but not exposed in the realtime-map api.

Closing this for now, but it is abolutely not impossible that i will figure it out some day!
