### ISSUE TITLE
[BUG] - Error on setting up integration: An unknown error occured. See logs for details.

### ISSUE THREAD

**Issue by KennoPa** [oven-lab/tuya_cloud_map_extractor#16]
**Describe the bug**
When adding valid credentials and pushing Submit, error occurs

**To Reproduce**
1. Add integration ->Tuya Cloud Map Extractor
2. Fill all required fields
3. Click SUBMIT
4. Red bar with error: "An unknown error occured. See logs for details." appears

**Expected behavior**
Successful integration setup process without error

**Screenshots**
None

**Version:**
 * Core: 2023.12.3
 * Supervisor: 2023.12.0
 * Operating System: Debian 11
 * Frontend 20231208.2
 * Integration: v1.2.0

**Log entry**
[tuya_err.txt](https://github.com/oven-lab/tuya_cloud_map_extractor/files/13742484/tuya_err.txt)

**Remarks**
What Tuya iot service API-s are required here, seems this is the issue in first glance?

**Comment by oven-lab** [comment]
Yes, that seems to be the problem.

make sure that you have the Sweeping Robot Open API added to the cloud platform (Main Menu -> Cloud -> Development - Service API and make sure to have Sweeping Robot Open Service added to the list of authorized services)

**Comment by KennoPa** [comment]
That was it!
Maybe adding the requirements to readme as well? 
Closing bug.
