### ISSUE TITLE
README : suggest adding 'what good looks like'

### ISSUE THREAD

**Issue by randomscot22** [oven-lab/tuya_cloud_map_extractor#17]
Firstly, thanks for building this !

I've been testing over the past releases and seen things evolving. I purchased one of the supported vacuums (SL60D) in the hope that the features (map and path) would appear, but given things are evolving difficult to understand what the 'expected behaviour' is (apart from looking at the Xiaomi extractor as a reference).

May I suggest adding into the README:

1. Which vacuum author is using for development.
2. A short picture (or video) showing what is seen on the card for the given release.

Thanks !

**Comment by oven-lab** [comment]
Thank you for the suggestions. Will definitely include it in the future!
