### ISSUE TITLE
Detail of supported device

### ISSUE THREAD

**Issue by randomscot22** [oven-lab/tuya_cloud_map_extractor#19]
I have a number of robots that I've been playing around with. I can report success with a Robot called 'W200' also known as:

KUANLITU W0200
Lydsto W200
GUANGDONG JOY INTELLIGENT W0200

This creates the following map:

![Map](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/97089145/d6d905c8-e4dd-4926-a063-34d209b85b3c)

**Comment by oven-lab** [comment]
Great! Will add to the list off supported devices.
