### ISSUE TITLE
[BUG] - Map format not supported

### ISSUE THREAD

**Issue by randomscot22** [oven-lab/tuya_cloud_map_extractor#20]
**Describe the bug**
Issue when adding ABIR R30 Robot (Unknown Error). When adding the device (with or without Path enabled) I get 'An unknown error occurred'

**Log entry**
Include the logs here. If possible, enable debug logging.

Source: custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py:147
Integration: Tuya Cloud Map Extractor ([documentation](https://github.com/oven-lab/tuya_cloud_map_extractor/blob/main/README.md), [issues](https://github.com/oven-lab/tuya_cloud_map_extractor/issues)) 
First occurred: 13:55:52 (7 occurrences) 
Last logged: 16:07:46

Unsupported data type. Include the following data in a github issue to request the data format to be added: 200b'AQABAAAAAAAAAAAAAAUAAAAAAAAAAAAA'b'eydyZXN1bHQnOiBbeydtYXBfdHlwZSc6IDAsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktZXUtc3RvcmFnZS1wZXJtYW5lbnQudHV5YWV1LmNvbS9kMDhkMTAtMTc1MzUyMTE1LWZoaDE0YmM1MjlmMjBjZmY3YTRmL2NvbW1vbi9sYXlvdXQvbGF5LmJpbj9DQz1kODQ4ZWY3NjEyYTI0ZDRjOGM1Y2VmNTM4YjljMjJiYiZDUz01MWE4YjNjNjU5YzcyZmRjN2NiMjMwY2E4ZTU5ZGY1NmQwYmZhNWU1M2UxYmI1ZDIzNDY5ZjFiMzhjYzdhMDFiJkNFPTE3MDQwMzQ1NjYwNjcmQ0E9VjEmQ1I9Mid9LCB7J21hcF90eXBlJzogMSwgJ21hcF91cmwnOiAnaHR0cHM6Ly90eS1ldS1zdG9yYWdlLXBlcm1hbmVudC50dXlhZXUuY29tL2QwOGQxMC0xNzUzNTIxMTUtZmhoMTRiYzUyOWYyMGNmZjdhNGYvY29tbW9uL3JvdXRlL3JvdS5iaW4/Q0M9ZDg0OGVmNzYxMmEyNGQ0YzhjNWNlZjUzOGI5YzIyYmImQ1M9ZjNiMDc5ZGQ3MWRjZWU5OWY3ZjgzZmQ3ZDY2MGRiNzE1YzQ0MmQ0NDYzZjYwYzgwNGFkZTlmZWVhZDM5YjEyMiZDRT0xNzA0MDM0NTY2MDcyJkNBPVYxJkNSPTInfSwgeydtYXBfdHlwZSc6IDMsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktZXUtc3RvcmFnZS1wZXJtYW5lbnQudHV5YWV1LmNvbS9kMDhkMTAtMTc1MzUyMTE1LWZoaDE0YmM1MjlmMjBjZmY3YTRmL2NvbW1vbi9yb3V0ZS9uYXYuYmluP0NDPWQ4NDhlZjc2MTJhMjRkNGM4YzVjZWY1MzhiOWMyMmJiJkNTPTk4YTBhZTk5MGVlZWQ0ODQ5NjY3MTA2OGQ3NzFhZTQ4MDc3NWE1MmFmZmE3YjQzNDEzZjE1ZTcxZGIzNTU2MGEmQ0U9MTcwNDAzNDU2NjA3NiZDQT1WMSZDUj0yJ31dLCAnc3VjY2Vzcyc6IFRydWUsICd0JzogMTcwNDAzMDk2NjA3OSwgJ3RpZCc6ICc1N2E3YTAxYWE3ZTQxMWVlYmRmY2ZhNzliOGUzZjRhNSd9' Thank you!

**Comment by oven-lab** [comment]
There is no map data returned from tuya servers. Unfortunately there is nothing i can do.
