### ISSUE TITLE
Map version [100] is not supported.

### ISSUE THREAD

**Issue by douglasfl** [oven-lab/tuya_cloud_map_extractor#25]
**Describe the bug**
Map version [100] is not supported.

My vaccum is a KaBuM! Smart 700, in tuya cloud is:
"model": "R530",
"name": "KaBuM!Robô aspirador de pó-R530"

This model is a rebrand of liectroux xr500.

**Version:**
 - OS: HAOS
 - Version 2024.1.5

**Log entry**
Include the logs here. If possible, enable debug logging.

Logger: custom_components.tuya_cloud_map_extractor.tuya_vacuum_map_extractor.main
Source: custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py:147
Integration: Tuya Cloud Map Extractor (documentation, issues)
First occurred: 09:11:52 (1 occurrences)
Last logged: 09:11:52

Unsupported data type. Include the following data in a github issue to request the data format to be added: 200b'ZNIBBQGCATQISAUACEQFHB9wH/8BAP////////////////////9eOfn5+WQQHPkRAAECAA8VAAIPAgD/NDj09PSCAVb5+fT09FoBA48BChUADwIA/yMIZQEJAgAU9IIBAGwBEfmAAQSCAQB3AQMCAAALAAk3AA8CAP8eAEgBD4QBBAAbAACFAQEGAA8CAAYPggH/MwdbBAcCAAd0ARsQAQAHGwAJqAQPAgD/IgJMAQ46AQIYAAECAAt+AQACAAEYAAUCAA4+AA8CAP8ZA0YBDjIBAxkAEPRwAQ4CAAQeAAMCAA4/AA8CAP8YAkMBG/91CgQYAA8AAwIOgQEPxQQDDwIA/xQAZQEBAgAMjAcBFQAPgQEVD4IB/zMMsQIAfwEPggQTD4EB/zEQ/0YBBoIBAfoLAGIKD4EB/1IBfAES9AYABVUKAH0BAAQAD4EB/18T9N0RABEDAIQNAXIHDQIAAR4ACgIABj4DDwIA/yEBSwEDAwMAeAEAhQEBCgAPgQH/VQBpAQICAATrAhT/CQAPAgAEAi4ACQIAD/gC/yEFAgAGSQEFcAEPggELBjEABgIABU4ADwIA/yIFRwEFgQEPAgALBTAABwIAD3gB/yIFAgANegEv//8DAwoHeAEFAgAFTQAPAgD/Iw2CAQ8CAAoFdQEIAgAPeAH/IwUCAA+BAf9vD4IBGgj4AgYCAAXNAQ8CAP8kD4EBGRYQdgEHAgAPeAHFACUQD9wAUQ+CARkHdwEGAgAPpQBRDwIAYAHhAA94AFEPgQEZDwMDAw8pAlMPAgBbAX8BABwQD3cAUA+CARkBlQAOAgAPpgBQDwIAWwbjAAwsGQ8CAEEP+BQEDwIAAQaZAAoCAA+XAEEPAgBnCdwAD4IBUA8DAxgJmwAIAgAPLgFnDwIAPwjYAA+GBFMPAwMXAZIADwIAAg8IAT0CGRoFAgAPXwA9DwIABg/dAAAPBANPDwMDFg+eAAAFAgAP0wAGDwIAIwORJwQCAAAoFw9JABgFuQEAAgAQ/wUABgIAD0cACwRxAAgCAA97ABoPAgAiDwMDFQiWAAwCAA95ACIPAgAIAZYbCgIACi4AD0sBCgg+ABn5DgAP2QgKCnAABQIAD4IBTg8DAxEFjgAPAgAECh4BDwIAMAk2AQMCAAcKAQ9LAQwIPgAPggEWA2YADgIAB3gADwIAQg+BAYIKuAIDAgAHCgEAggEHDwAMAgAMggEUHAEACUUACAIAA2MADwIAAg9pAAgPAgAyD4IBEA+YAAIHAgAPiAAyCgIACEQBBAIAAwoBANMFABMAAw8ADwIAAQg+AADpIQSBAS8cHIYEBQBRAA8CAAUPaQAIDwIAMQ+BAYMOBAMAeAECfgEEXwEIGQEAHgAHEAAEIwABAgAPggGLAKsAD3gNAQgCAAHHAA8CAAgPCAIxDgIADHEAAWQBAv0CAwIAB3IBAbEBBxAAANcABQIAIPn5/QIDAgAPBAMEAFsADwIAAQFFAAdZAA8CAD8f+YEBhQFUAQ4CAAhbAQgZAQAYAAcQAAAPAAUCAAmCARgcJgAPdAEBBgIAAIUAAg4AD3gBPwYCAA+CAQ4FyAAPAgAFBkwADwIAOwlFAQV7AQkWAAhNAQGbBwQCAAEPAAQCABv5ggEEJQAGzwQHAgAHFQABIgAAAgAP2AA7DAIADwMDDQedAA8CAAMMUQAPAgA2CWwBE/QQBAHDJAECAACOAAdsAAJpBAIGACQc+bwCBAIAA4IEDwIAHABjAANzAAQPAwdyAA8CADQPAwMNAYMADwIACA+HADQPAgABD4IBBAMrAAEeAAQYAQACAAheAQAQAAkCAAgdAA8CABoD+wAAbQMAcgAACAAPAgA6AEoCCHMHDQIAA4EADwIABg+OADoLAgAA8gAGAgAAqwAAAgAEBAEE+ggFJgAPWQEaDwIAGQR2AABqAAR+AA8CADYPAgOIAWQBDwIAEQ98AUgFAgACegMAiwEAmQAPAgA3AHUGDfYCBwIAAHIADwIACg+LADcPAgABAHQCDwIAEQUoAQ8CAEcCggEAkQAPBQM7DwIDDA/+AA4PNwEBDwIAOAhHDQ8CAGwGggEP9gA5DwIDjATeCA8CAHIEggkPggE8D4UHCwBtAA8CAAoAJQEPAgBKA1oKDwIAcQA/MQCXCgAGAA+IBDcPBAaKAAIAD4IBfwECAA+CARYBLgACwAQPAgADD4IBCgI+AA8CAAgPVAADDwIAOg+CAc03+fn59wgLAgAPewEIAgIAD2sBOg8CAAQPggF6ADYHAfsAH/8EAzQATQAPggEHAB4ADwIACg80AQQPAgA7D4IBVg8zDwEKFAACTAQCngwP5QAVAi4ADzAABgBgAQ8FAwYAHQAPAgAJD4QAFQ8CACwPggFYDmsAD4IBBw8CAB0PBgEEAGEBD4gEBQAcAA8CAAkPUwAEDwIAPg4XAQ8CAEIGbAEGCgAA3RMBBgADAgACBAMAFQECkgoPAgAYD7UEBAHUBANBFAsDBg8VKgQGAgAPagE+DwIABQ+CAVQHbAEIcgAJjwEBVBgBHgAOMAEPAgAMD4IBBQFLAwKsBAtCAAZrAQ8CAAMPMAEFDwIAPwHyAA8CAFwGeAEGCgAAAgAASAEBkAANMAEPAgANAWoBDwIACA1AAA93AQMGAgAPaQE/DwIABgHyAA8CAHQPggEnDwIABQ8ICQUGawEPAgADDy8BBg8CAEAPggF9EP8OAg+1AgAPAgAjD4IBBA93AQMGAgAPaAFADwIABw+CAeEGawEPAgADDy4BBw8CAEEPggF+AAUDDwQDSw93AQMGAgAPZwFBDwIACA+CAd8GawEPAgADDy0BCA8CAEIPggFfD3IABwCKBxD/HwAPBANJD3cBAwYCAA9mAUIPAgAJAPEADwIAUAZ3CgYKAA0CAA+CAVEGawEPAgACDysBCQ8CAEQPggFUB5INAEskBX0BBwsAD4IBUg93AQIGAgAPZQFEDwIACg+CAWEBagQCAgAJfwAPBANPBmwBDwIAAg8qAQoPAgBFCQMBDwIAIw90EwENAgAH7QIPggFnD3cBAgYCAA9kAUUPAgALD4IBDw/tDwgFAgANcQENAgAGJAAANQAEHwAGCgAAAgACBAMAIAAPSg0EDwIAHgpIAABsAQbbTA0CAA8pAQsPAgBGD4IBEA98AA0PQwAPDwIAFAGCAQECAAo6AQ8CACcJSAADZAENegEDAgABeQAPAgBgDz8BDwGUAg8CAAoPYQEUDwIADQcZGwk6AQ8CACgJSAAAYAADbgEPAgAAD3wBYAICAA+CAQ8PAgBWApEAAQIACToBDwIAKAhIAA+AAQoPLkJoD4IBeAaFBBj/OgEPAgApCEgADwQGgQACAA+CAZMPBQUKAAIAD6cBDw95BAAIAgAADAEPAgBjD4IBlAMjCQACAA8oAQEPgwEPCG4BDwIAAQ9WAAEPAgBTD4IBlgTmAg8XAQMIbwQPAgACD3YBAQgCAA9XAAMPAgBRD4IBVQhoAAY+CQYKAACuEAbwAAxRAQ+CASQHGwMIbgEPAgAABnsADwIAXggaAQ0CAAD1AwklAQ8CAAIAJAANAgAMKgAGaAAAKwAEHgAGCgAPggFrD3cBXgcCAAYaAQ8CAAABnggPIgAKAAIAASYACwIACVsBDwIAFAfjBQ8EAwMBDQYLaQADAgAMMQACAgAPBAMVA0UADwIAYw9gAQoBXAEAtAIPAgALD7oAAQ9YAAoPAgAEAW8AAQIADFEBA/QjARwADwIAAgwxAAICAA+CARMPUQACDwIAVw8qAQoGEwEPAgAdEPltHA8CAB0BbwAC7QECQgEFAgABGgAPAgAJD4IBBAVBAA+hJQgPVwAJDwIAUQ+CAUUKfgEHlQQPcQAIAmgBPxwcEIIBWQ9lAVEPAgAKDxEBCAQTAQ8CACEMVwAGEAAHjQEMAgAPggFID/8IAAICAA/dACEPAgA7BhsBDwIAAAITAQ8CACEPVwAKBzEbCSgAAm8ADwQDIQ01AwICAAYXAAJvAQgCAAFUKg8PEmgFAgAJAwEMAgACEwEPAgAhD1cACg+CAQsAUAEM1wUCHQYPAgAIAnIBDAIABRgACHsBAgIAAh0sAG4ADwIAbQ8rAQoPggFFDwIAAwfsCAyCAQ8CACQPggEHAnhmD+AAJw8CADgPggF4BxUPD4IBPAL3AggCAAJ8AQIGAA8CAGwPggF6BRIBD4IBTg92AWwIAgANXAUIIgQFEgEPAgAeD9kBCg8CAAYGjQAPdwQkCwIAA0gACP0CAwIAD9EAHg8CAFYKOgEPggFdAwIAC0gBDwIAJw+CAQYP2QAnDwIATwMFAQICAA+pACcKygEXHFsDCxoADwIAAQ9zAScLAgACggED9wIIAgAP2QAnDwIATwkSAQ+pACcMaAEGEAAAVAAGDgAPAgACC0gBDwIAJw+CAaIJHQEALgEPAgAjCUcADQIABh4ABgoABwIAD3MBJwsCAAGCAQj8AgQCAA/ZACcPAgBPCRMBD6kAJwlHAA8CAAgPKAACC0gBDwIAJwHbDQR2AQcCAAd6DA8CAH8JEwEPggE5BwsGBgIACW4ABQIAD3MBJwsCAABbGwd5AQUCAA/YACcPAgBQCRQBD6oAJwlHAAECAA+CAQEPFAABD4IBPAV2AQgCAA/YACcPAgArD3gAAQaCCwQCAAEEAQMCAA8yAAEPAgATDoIBDwIAAg8nAAMLygIPAgAnC45cBQIAD9gAJw8CACsPDhQBDwMBAwQCAA+qACcPWAALDwIADA9zAScLAgAPggF9AjcsA/gCAs0BCvMCDQIAD4IB/0cAGBcCXQEPZk4MAiUADwIAIQ8EA4oEgAIPAgBhAY9KAY4EA/cFDfcCCQIAAyUADwIAIQlIAA8CABwLTAQPAgAnA+wADQIAD1oCJw8CACwBigADlgABohgPKQErDwIARg9zAScLAgAD7AANAgAPBQNmAYoAA5YAAYIBH/QtBCoPAgBGC0gBDwIAJwW0SwwCAA8FA2QAfgQCUQQAfAEADgAPggHNA+YADgIAD4IBZAIMCRD0/iQAoy8AmAAPBAPMD4IBBw+DAWQBHB0CykoCEgMPBAPmBAUBDwIAXwH4AgJ3AA+GBOoPpiJnAgcGAAIAAYYEDwwJzQ+GBAYPggFnAQIAAP4CAQkADzkNLA8CAEYP/QgnCwIAD4IBBQEJBw8CAGgPggHwD34BaAGJBAaGAw8MCeQPCglkBAIAAI4HBAgFD4IBnwDEBgsCAAt7BAcCAA+GBAYEDAEPAgBhAYABBQoFD4IBoA01AQ/eJQgPggEEDwcGagB+AQECAAKJAw+CAeQNxgEPAgBXAX0BAQIAAggCD4IBsg+IBAcPBAMDAGBCDwIAZQF8AQMCAAEFAw+CAZEL9gUPPAEAD4gEBg+CAQQPQwAADwIAUwN7AQMCAA+CAZcDHgEDigEDDgAIAgAPggEQAD0AA/kAD4IBZwSBAAMCAA+CAZ8BuQABtwALAgAPggEFAVNiAP4MATcAAhYTCzsADwIAWQCIAAgCAAHLAA+GBAwAOgIPAgACDg8PAicADhgADwIAEA07AAdQCgFnGQInAQNLAQQPAAQCAAA+AAECgAAJAAwCAAQEFgN9Bww8AA8CAFkIfAECAgABjgAPggEND6MABA5rAQHtAAAVBw9yARALAgABNgEJfTkBeQEFAgABqQAAXQADuAAEEAADAgAAXwEBQwALGAAAAgACGAABAgAADwAPAgBpAr0ACQIAAbEAD4IBJAkwAQECAAFOAA8ZAAEPAgAPAIQACP1PD4IBBQPfGAPPAgUCAA4SAAYCAAA3AwEABgYTAA8CAGQJewEDAgABNAEPtAIMASQADwIAAQA2AQkCAAQqAA0ZAA8CAA8AMwAPggEIBXIBA7gAC08BABEABH0ADQIAAIIBAQIAD4EKaQY8AgsCAAK3AAD/AA8CAAcCJAAPAgAADTcABCoADRkADwIADwAzAA+CARAGvwAHkAADFQAHEgAJAgAFggEE7wAPAgBjAIAADwIAAAI0AQ8xJAsCJAAPAgAAADYBCQIABCoADRkADwIADwAzAA+CASwEfgAMAgAPggFzD30BAAPOBgGiBg8CAAQCNgAP2gAFDwgGHA9kAAQDnQEPggFIBL4HAPMADJ4BDwIAVQF+AAsCAAQ3CAAXAA9kAQQENAEPpwAFBCAABgIAAyoATfn5+QQBAA9lAAMEfwMJggEADQAFBgkBAgAEPAEEFgILdAQAEQAEIwAPAgAABKEAAScADyAAAA8CAE4BeQAKAgAEgAECHQAPHQEDDwIAKg6EAQAHAQ5TAAAWAAUCAADJCg8CAAUDOwADRwEMSQEBNgADIwANAgADngEDjgQP7QBADwIADACvAA0CAAKHAACIAQAbAAIOAA8CADsOBgMPaAApAGIBAEkBAAgAAgIAD64AGAA5AAaNBA85ABgPAgAzAGIBDgIAAnQBAxYCAKAAAtcADwIACQ+PABwOggEQBGgADwIAIgRWEA/PEQ4AUwIOYgAENwAPQQAQDwIAQAF2AAwCAASnAAIYAAJ3AQIMAB30vwUEAgACJgAPAgAYBDkABwIADz4AFQ0IAQOdAABLAQREAAEkAAQNAAEPAAAHAAJPAg8CAAQBJgAPAgBcAbUADgIAA4IBAwMDEPkKAAcoAQ8CADIPAwMAAIgEDwIAEgOfAAcCAAY3AAQUDw/iDAYBGwAPAgB2AJAADwIAAQTjAAAyAgG5Aw8wAQIPAgAqD1IAKA+tBAAOxQAEigEPAgAABN4ADwIAcA+eAAAAAgAGHhQAuAMBqAAPMAEoDwIABA9SACkFlwAEAgADrQMPAgAUD4IBdg+wAAYE2AAHAgAPMAEpDwIAAw9SACoMRgEAkwEHzwAPkQEMD4IBdQeyAAsCAAd6AQQCAA8wASoPAgACD1IAKwEdBQACAAOhAAV0AQUJAA8CAAgPggF0D6IABwPVAAkCAA8wASsPAgA/BNsdAIUBAFEBBXkBD/8FCAUCAAAxAA8CAHAFkAANAgAPnQABD4IBhQACAAGGAQAJAAACAA+CARIPgwFzAK8ACwIAAvQPD4EBAQ+CAYoAAgAGgwEFDgMPAgAID4IBcgE5AgwCAA99AQIBAgAPggGNDwIAGwG6BAAzAA+LAXIPAgATD4IBuwUCAA+CAf////91AQ8GDwIAlQ8IBsIPBgaYD4IBQg/VASoEkg0PAgAqD4IB7Q8CACoPggHeD08ZAg8CAGkPggHfDxsbBw8CAGMPggH/bgHMDw8DBioBAgAPCAaZD6UcPw8CACoAOwEPABIRDwIADABHAA8CAJUPCAZADwsJKQA7AQ+CAdwCNhUB+QABAgQPAgAyDwcDAANYAAsaAAMWAAcCAAWSAAoCAA/0AgwMAgAA0AAPAgDpDwUDAQIUAQwaAAIWAA8CABAMYwEPAgAMD1gAFg8CAMQMaAEAAgACFAEK2QICfAMPAgATD3MBDAsCAAJuAA8CAHcB7AABAgAIDAAPAgARD5sEEA7nAA1sBAACAAQUAQx2AAA/AAwUAAECAAR7AAAhAAICAAEXAA8lBhMEbgAPAgB1BbYAAaElCy8CDgIABnYFAxVQDwIACQfsAAIiAQ89LQIHggEKTQABYgEPlAABBGwBBmAjAwIACkAADwIABABOBgMwAA8CAHIy+fQAAQAAggECCgAPAgAJJPn5HgAf+S8AAgn2AASCAQB7AQBqAQ8CAAQFiyUo+QgBAAA4JgCgAAlTAAECAAYUAARiAAQCAAEfAAcCAAYqAAsCAAQxAA8CAHAHUgEPUwECCwIAD4IBDRgA6gAAegEBAgAPewEEAwIAAGkBAQIACoIBMAgICJQAAQkACgIABCgADoIBCoQBBCwDBAIAB5ABDT8DDwIAZwmCAQUNAAECAAA9AQEJAAMCAAAQAAYSAA8EAwMAAgAAJgADAgAP9CsJBQIAD4IBCABHAAp+AQACAASCARUIOgAHAgAEbwEAQwMBBgAR9BQAAEoAC1IhBzUADwIAaQV1AQDoUgBAAQ8CAAsGJAAPggEHCQIAD1sSEAFIAQAiAQ9uAQEPAgABD4IBCgFwAQkCAAAUAAICAAkXAAF3AA8CAHAAggEA/AAAAgAJOwEPAgADBiUAD4IBPQATAQVbAQ8CAAsFJwAPRQEFCGoBCWQBCBkAD0NCZwoCAACCAQ8CABgPggGTCG8EDK0HBhwACgkBDwIAZg+CAScGjQEPAgAJD4YEFgEEAwXeAg8CAAoFJgAPCCcIBe4CDYIBA4UBAQkADwIAcQ+CARwPAgAeD4IBGR8ICQYVBAIAD2ABAwMCAAOEAQFWDA8CAIkPggF2AFYBD4IBOgRvBA9+AYkAAgAPggF8BWEEDwIAEw+LBwUDAgABBwMDDAAPAgCGD4IBeg+HBB8P5gUBCAIAD/MIdw8CAAYPggHMDwIAkA+CAX0PhwQbD4YEDA8CAJIPggF7D4cEHQ+CAf9BHwgEA/9vDwIAHA8EA/8VAHMSD50cAQQCAAFHAQ/8AhsEAgABOwAPAgCsDwgGTgI6EA+CAf9JAeECDwIACwCkAgoiAAT+AgECAAKUHw8EAxwFUAAAXQAPAgCrDwQDLQ8TDQ0PAgABCoMBAkIAD4IB9AqPAQBoAgiKEwoOAAMCAAJAAQ8CABsJggEDywUPggEdAgoGAz0ADwIAqgl1AQkNAA+AFhMPggEiAX4EAwIAA0UBD4IB9A8CACACggEALwMPAgAGAKICCh0AA30BAQIAD4IB/zYAhhQBmR8OAgABpAEHpyALvh8PggH/PB0YAQAA+hoBBAMm9AwBAAGGAQUCAAGiAQIgGA8CABcDtQQCXQAPAgCrCvsFDwIAHwNAAU/09PQYggEBExhiARb5gAELAgADRQEDUwEPAgAVAy8AAz0ADwIAqg+CATQPfgECAAIAD4IB/1QAZwcAbgEPAgABD4IB/1UPewEBAwIAAyYcD4YE/00T+W4BDwIAAQOqBQ+CASQD7wUOAgADGQADXgAPAgCqDwgGMQ+CAQoCHgEPggEjAN8EA2wBCwIAAxYAD4IB/xECgAEPggEpC3sBAwIAAZwBAAIAAF0ADwIAqw8EA0sCrAoA7wsLhAoGAgADxwID1QIPAgAVAH0BAQIAAV4ADwIAqg+CAUsPCAYtDwIADQO/AQ8CAKoPggFGAx0GAyQBDwgGIw8CAA4DXgAPAgCqD4IBRgMCAAMkAQ+CAf///w8CNg8PigccAwIAA2IDDwIAqg+GBEMDBQYAmhMCrwgPhgQID4IB+gqPAQDuCQgtFQoOAAMCAABwCgZwATAYGBg2AAcnEgJgAQ+OCggSDCIADwQD9A2CAQNnAQ8CAAgNggEFAgAR/woAAmABD4IBCREMSwQPggH0DAIACpIBDwIAAg+CATYAOgMPAg8FDwIABgG9AQ8CAKwPZQEQDwIACg+CAQcCAgAPBAMVD4MBIw+CAf88ALccDwUDHQ+CAf8aAGMEAgIABhMSAwIAA0cBD4IB/0YTGGABBQIADpgKAyIAD4IB/z0C7wICAgAFfQEBAgAOBQMDggEA/DgPhgT/OQChBw8CAAMPBAMGAAIAD4IB/zgM+QIPCAYRAQIADxcMHAQ/Aw8CAKkPjgpEDAQDDvoCBgIACEcBD4IB/3EPGR4FDwIAAwi9AQ8CAKUPBANFAoUHAQIAABsBDwQDFQCxBA9tAQMPAgACD4IBvAAvAQ8ADwoPAgABAG8ECZoTDAIAAiUBD4IB/xEAfwECAgAPaAEBDwIABw+CAf82B3gBF/kMAA8CABAPggH/NQoNBg+DARoPggEtAXgDAQAGBAIADw8JGQLjBA8CAKsKfQECAgAPFAABDwIABQ+CASwLfgEAAgAPggHxD4MBGQ+CAS4AAgAAeQEFAgAPggHyD4MBGA+CASwAAgALSwQPggH//////34f//sIBQ0CAA8IBv9GD4IB///zDwIAFwGGBA+bEwkCbAoPmhP/EQ8CACUPggH/dQySFggCAA8EA/9UCHIBDAIAD4IB/ygPHBIUAYYEDHYBCAIAD4IB/zYPshYGD4IBFSj09F5FCQIAAqQBBQIADxgS8wBzAQkFAwsPAAYCAA+CARUAAxUPAgAGBX4BAAIADyYABg8CAAIAMgAPAgCrCWgBBwIADPUCDBAABAIAD4IBDQM8LQ8CAP8JD4IBBQ8CABUPggH///IBiQUPEw8KC2gHDwIA/wAPhgT/sQC1WAgADAsCAA+KB/9QAI91C3UBCQIAD4IB/1MJcgEMAgAPggH//5QAag4ATQQPAgAmHPT3AgkCAA8EA/8UD3MQBg8CABIPggH/NQ+VCigPggH/NA3tAg8TAAAPAgAFD4IB/y8PCAYDCxYDCw8ACQIAD4IB/y8JTgEFAgAKcwEPpgEDAwIAD4IB/0UPAgAYD4IB/////3YAZmMAKAYHAgAIkw0Pkg3/FA8CACkBeQEK9RcJLxgPggH/Tw+AGQEBlQEHAgAKoAEPAgD+Dw0PKAACAA+CAQEPAgD/HQ+CAf////////////////////////////////////+8B18fDwIAEQDPqABQPA8CAP8sAEIBAG4BD3cfFQAsAAQCAAG8Zw9/Af8sBgIAA1UBBhEADwIABQaBig+CAf89DwIAFg+CAf///QJHrgBIBg8CAP9cBoYED4IB/////24DuAoAAgAPEAz/Ow8CACEAhQEPQwwRDwIA/////////////////////////////////////////////zxQ//////8='b'eydyZXN1bHQnOiBbeydtYXBfdHlwZSc6IDAsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktdXMtc3RvcmFnZS1wZXJtYW5lbnQuaW90YmluZy5jb20vMzEyM2ViLTMyMDgyNDg0LTEyM3dhNzg4NzllNDZhNGE5ODA0L2NvbW1vbi9sYXlvdXQvbGF5LmJpbj9DQz1kODQ4ZWY3NjEyYTI0ZDRjOGM1Y2VmNTM4YjljMjJiYiZDUz1kZjUwNjM5Y2I2MDFlYmJmYjdiNmM4NTFkNDRmYzg4YmRkYjc2Njk2YjZiOGQ5OWRmZTBiNTlhM2VhMTJmZmIwJkNFPTE3MDYyNzQ3MTE1NTQmQ0E9VjEmQ1I9Mid9LCB7J21hcF90eXBlJzogMSwgJ21hcF91cmwnOiAnaHR0cHM6Ly90eS11cy1zdG9yYWdlLXBlcm1hbmVudC5pb3RiaW5nLmNvbS8zMTIzZWItMzIwODI0ODQtMTIzd2E3ODg3OWU0NmE0YTk4MDQvY29tbW9uL3JvdXRlL3JvdS5iaW4/Q0M9ZDg0OGVmNzYxMmEyNGQ0YzhjNWNlZjUzOGI5YzIyYmImQ1M9Njc0Yzk2ZjZmNmE4MjllMDVhNGEyY2YzNWZlYjU0MDdmOGNhYzRhYzM5NGY4MGFkM2I5NmI4ZDIwYTA4NzVkYyZDRT0xNzA2Mjc0NzExNTU4JkNBPVYxJkNSPTInfSwgeydtYXBfdHlwZSc6IDMsICdtYXBfdXJsJzogJ2h0dHBzOi8vdHktdXMtc3RvcmFnZS1wZXJtYW5lbnQuaW90YmluZy5jb20vMzEyM2ViLTMyMDgyNDg0LTEyM3dhNzg4NzllNDZhNGE5ODA0L2NvbW1vbi9yb3V0ZS9uYXYuYmluP0NDPWQ4NDhlZjc2MTJhMjRkNGM4YzVjZWY1MzhiOWMyMmJiJkNTPTRjYmI4NmExODA0MWJmYTNjNjBkZDA3NDQ4MjVjZGI1YjI5OTdiNWM0Y2YxYjQ3NDY4NjNiZTVhNzU2ZTJjNDEmQ0U9MTcwNjI3NDcxMTU2MSZDQT1WMSZDUj0yJ31dLCAnc3VjY2Vzcyc6IFRydWUsICd0JzogMTcwNjI3MTExMTU2MywgJ3RpZCc6ICcxNjZhZGZmMWJjNDQxMWVlYTU0YzIyZjA2YzAzNzdmOCd9' Thank you!

**Comment by andrempo** [comment]
Probably same as #11   (XR500 has two motherboard versions)

**Comment by oven-lab** [comment]
Unsupported data format, which is not well documented by tuya. Will look into in the future, although closing as not planned right now.
