### ISSUE TITLE
[BUG] - Map format not supported

### ISSUE THREAD

**Issue by Erfurt24** [oven-lab/tuya_cloud_map_extractor#27]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - OS: [e.g. Home Assistant OS.]
 - Version [e.g. 2023.11.2]

**Log entry**
Include the logs here. If possible, enable debug logging.

**Comment by oven-lab** [comment]
Not a valid issue.
