### ISSUE TITLE
[BUG] - only last path is shown for run in 'mopping mode'

### ISSUE THREAD

**Issue by randomscot22** [oven-lab/tuya_cloud_map_extractor#33]
**Describe the bug**
For robots that offer a mopping mode, it is common for the robot to return to the base to empty water on a regular (6 / 9 / 12 min) basis. The current code seems only to show the result of the last path from the dock, whereas the Tuya app shows the entire cleaned path from when the run was started to it completing (involving multiple water changes).

**To Reproduce**
Run a robot in a large area in mopping model.

**Expected behavior**
Expect the path to show the entire cleaning cycle from cleaning start to dock/charge at end.

I expect the robot has 2 sets of map files, a 'total cycle' map and a 'last cycle' map..

**Comment by oven-lab** [comment]
This is a known limitation from the tuya open api. There is nothing to do until local communications are figured out.
