### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by gilbranmennabarreto** [oven-lab/tuya_cloud_map_extractor#4]
Hello folks,

I'm trying to use your extractor, but I'm not able to install.

It's always returnin that my subscription is expired.

```
File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 58, in async_step_user
    info = await validate(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/config_flow.py", line 95, in validate
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/main.py", line 91, in get_map
    map_link = get_download_link(server, client_id, secret_key, device_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_cloud_map_extractor/tuya_vacuum_map_extractor/tuya.py", line 69, in get_download_link
    raise RuntimeError("Request failed - Response: ", response)
RuntimeError: ('Request failed - Response: ', {'code': 28841002, 'msg': 'No permissions. Your subscription to cloud development plan has expired.', 'success': False, 't': 1701176617210, 'tid': '8b2f38578dee11eebeb4027cbd1575e0'})

```

I have a Liectrux XR-500

I'm not sure how to fix that, can you help?

**Comment by oven-lab** [comment]
[More docs](https://www.home-assistant.io/integrations/tuya/#28841002-no-permissions-your-subscription-to-cloud-development-plan-has-expired)

**Comment by gilbranmennabarreto** [comment]
The initial trial is comming for only 1 month. I've requested the extension and will let you know if it works. If yes, we can update to add the XR-500 as compatible. Keep you posted.

**Comment by gilbranmennabarreto** [comment]
It worked 
<img width="511" alt="Screenshot 2023-11-28 at 18 36 39" src="https://github.com/oven-lab/tuya_cloud_map_extractor/assets/145641494/6634611f-4fb9-4dfa-aea0-3ce4c9a008ff">


Liectroux xr-500 is compatible

**Comment by oven-lab** [comment]
Great! Thank you!

**Comment by mitchoklemen** [comment]
Oven...
My Vacuum is Neatsvor x600 pro  
[https://neatsvor.com/products/neatsvor-x600-pro]
... if you list it

**Comment by Lippyn** [comment]
Does on-premises Tuya integration expire with Tuya IoT Core? If it doesn't expire, you could add a local integration
