### ISSUE TITLE
Current vacuum position and path support not working.

### ISSUE THREAD

**Issue by oven-lab** [oven-lab/tuya_cloud_map_extractor#6]
Currently, the only thing this custom integration supports is showing the map generated by the vacuum robot. Which in it self is not very useful. Therefore, it would be great if the vacuums current position was shown on the map, as well as the path where it has already cleaned.

To get the support to where we are now, i have used the following:
* [Tuya panel demo](https://github.com/tuya/tuya-panel-demo/tree/main/examples/laserSweepRobot/src/protocol) With the [docs](https://developer.tuya.com/en/docs/iot/laser-sweep-robot-template?id=Kae3e76wphrun#title-5-Modify%20room%20names) as a little help.
* [Xiaomi cloud map extractor repository](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/tree/master/custom_components/xiaomi_cloud_map_extractor), where the roidmi protocol works to translate positions for the elvita protocol.
* [Tuya API Docs](https://developer.tuya.com/en/docs/cloud/b424c92fea?id=Kb9pe323jk3zq)

After rewriting the functions for the tuya v1 protocol, i did get a path, that was inside the image frame, but not in logical places.
I'll add the files if anyone else wants to scratch their heads over it!
[robot files.zip](https://github.com/oven-lab/tuya_cloud_map_extractor/files/13539478/robot.files.zip) - Map data
[extract_route.zip](https://github.com/oven-lab/tuya_cloud_map_extractor/files/13539665/extract_route.zip) - all the files needed to get to where i am right now with the route extraction.

**Comment by mitchoklemen** [comment]
Hi,

The path seems OK, as I runed "test run" before I sent the debug file to your expertie :)
Can you include the path to new version?
Thank you, Mitcho

**Comment by mitchoklemen** [comment]
Hi, I get error... can you check?


Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:359
Integration: Kamera (documentation, issues)
First occurred: 14:36:42 (2 occurrences)
Last logged: 14:40:07

Error while setting up tuya_cloud_map_extractor platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_cloud_map_extractor/camera.py", line 36, in async_setup_entry
    colors = config.data["colors"]
             ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'colors'

**Comment by mitchoklemen** [comment]
sorry, as I started from "start". All is OK. "Old" entity didnt work.

Thank you for new version!

**Comment by oven-lab** [comment]
Good to know, I'll fix it for the release.

**Comment by mitchoklemen** [comment]
Path color is not showed like I set in the setup. I set it Black color.
![camera](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/38099509/53efb0e5-8cf8-492a-9df2-239566ee9c51)

**Comment by oven-lab** [comment]
Then I'll fix that as well!

**Comment by oven-lab** [comment]
Question @mitchoklemen, Does the path go through walls in the app? Or are there parts of the map that incorrectly shows up as walls in home assistant?

**Comment by mitchoklemen** [comment]
Most are OK, I think that where Vacuum ends in one room, the line goes direct to the start in second room.
![camera1](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/38099509/5f62f6a0-4187-474f-8a0f-610f6668e701)

**Comment by mitchoklemen** [comment]
i setup the new b2 version and there is current Vacuum place (blue dot). In b1 ver. there was room names like in the app, but not in b2 ver. b2 is preety much clearer than b1.
![camera2](https://github.com/oven-lab/tuya_cloud_map_extractor/assets/38099509/408bd1d5-0a74-4828-9d13-77c81788b231)

**Comment by mitchoklemen** [comment]
For me, all good now, except realtime current possition. b2 calibration works good.
Now we wait for manual location clean, remote control, no go zone, ...

**Comment by oven-lab** [comment]
I can fix a wider path, bigger location dot, and charger location within the next couple of days. But the other features can be a bit into the future. I have to focus on getting all vacuums to the state where you are now first.

**Comment by mitchoklemen** [comment]
Great! No rush for new stuff. Thank you very much!
